# Generated by Django 3.2.8 on 2022-01-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
